from repositories.crud_tbl_document_type import crud_tbl_document_type
from repositories.crud_tbl_permissions import crud_tbl_permissions
from repositories.crud_tbl_rolepermissions import crud_tbl_rolepermissions
from repositories.crud_tbl_roles import crud_tbl_roles
from repositories.crud_tbl_users import crud_tbl_users
from repositories.crud_tbl_userroles import crud_tbl_userroles
