from schemas.pdf_scraper.document_metadata_schema import DocumentMetadataSchema
from schemas.pdf_scraper.document_type_schema import DocumentTypeSchema
from schemas.pdf_scraper.documents_schema import DocumentsSchema
from schemas.pdf_scraper.file_storage_schema import FileStorageSchema
from schemas.pdf_scraper.scraped_law_status_schema import ScrapedLawStatusSchema
