"""tbl_document

Revision ID: 20c2fabf37d9
Revises: 817275a8b522
Create Date: 2025-03-15 19:29:40.019089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c2fabf37d9'
down_revision: Union[str, None] = '817275a8b522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tbl_Documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_description', sa.String(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('the_document', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['Tbl_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Documents_id'), 'Tbl_Documents', ['id'], unique=False)
    op.create_index(op.f('ix_Tbl_Documents_is_uploaded'), 'Tbl_Documents', ['is_uploaded'], unique=False)
    op.create_index(op.f('ix_Tbl_Documents_uploaded_at'), 'Tbl_Documents', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tbl_Documents_uploaded_at'), table_name='Tbl_Documents')
    op.drop_index(op.f('ix_Tbl_Documents_is_uploaded'), table_name='Tbl_Documents')
    op.drop_index(op.f('ix_Tbl_Documents_id'), table_name='Tbl_Documents')
    op.drop_table('Tbl_Documents')
    # ### end Alembic commands ###
