"""Documents and Metadata tables

Revision ID: 241a9ac2b867
Revises: 817275a8b522
Create Date: 2025-01-19 10:07:35.604644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '241a9ac2b867'
down_revision: Union[str, None] = '817275a8b522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tbl_Document_Type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('document_extention', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Document_Type_document_extention'), 'Tbl_Document_Type', ['document_extention'], unique=False)
    op.create_index(op.f('ix_Tbl_Document_Type_document_type'), 'Tbl_Document_Type', ['document_type'], unique=False)
    op.create_index(op.f('ix_Tbl_Document_Type_id'), 'Tbl_Document_Type', ['id'], unique=False)
    op.create_table('Tbl_Documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_description', sa.String(), nullable=True),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('is_uploaded', sa.Boolean(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['Tbl_Document_Type.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['Tbl_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Documents_document_type_id'), 'Tbl_Documents', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_Tbl_Documents_id'), 'Tbl_Documents', ['id'], unique=False)
    op.create_index(op.f('ix_Tbl_Documents_is_uploaded'), 'Tbl_Documents', ['is_uploaded'], unique=False)
    op.create_index(op.f('ix_Tbl_Documents_uploaded_at'), 'Tbl_Documents', ['uploaded_at'], unique=False)
    op.create_table('Tbl_Document_Metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('teu', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('law_doc_type', sa.String(), nullable=True),
    sa.Column('law_doc_type_abbr', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('place_of_confirmation', sa.String(), nullable=True),
    sa.Column('date_of_confirmation', sa.Date(), nullable=True),
    sa.Column('date_of_enactment', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('url_source', sa.String(), nullable=True),
    sa.Column('document_url_source', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('valid_status', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['Tbl_Documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Document_Metadata_id'), 'Tbl_Document_Metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tbl_Document_Metadata_id'), table_name='Tbl_Document_Metadata')
    op.drop_table('Tbl_Document_Metadata')
    op.drop_index(op.f('ix_Tbl_Documents_uploaded_at'), table_name='Tbl_Documents')
    op.drop_index(op.f('ix_Tbl_Documents_is_uploaded'), table_name='Tbl_Documents')
    op.drop_index(op.f('ix_Tbl_Documents_id'), table_name='Tbl_Documents')
    op.drop_index(op.f('ix_Tbl_Documents_document_type_id'), table_name='Tbl_Documents')
    op.drop_table('Tbl_Documents')
    op.drop_index(op.f('ix_Tbl_Document_Type_id'), table_name='Tbl_Document_Type')
    op.drop_index(op.f('ix_Tbl_Document_Type_document_type'), table_name='Tbl_Document_Type')
    op.drop_index(op.f('ix_Tbl_Document_Type_document_extention'), table_name='Tbl_Document_Type')
    op.drop_table('Tbl_Document_Type')
    # ### end Alembic commands ###
