"""Update Tbl_Document_Metadata

Revision ID: 5f375935e1cd
Revises: a3535421f1ff
Create Date: 2025-01-25 17:35:49.166922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f375935e1cd'
down_revision: Union[str, None] = 'a3535421f1ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tbl_Document_Metadata', sa.Column('about', sa.String(), nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('changed_by_other_law', sa.JSON(), nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('removing_other_law', sa.JSON(), nullable=True))
    op.alter_column('Tbl_Document_Metadata', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('Tbl_Document_Metadata', 'subject')
    op.drop_column('Tbl_Document_Metadata', 'valid_status')
    op.drop_column('Tbl_Document_Metadata', 'location')
    op.drop_column('Tbl_Document_Metadata', 'document_url_source')
    op.drop_column('Tbl_Document_Metadata', 'teu')
    op.drop_column('Tbl_Document_Metadata', 'url_source')
    op.drop_column('Tbl_Document_Metadata', 'law_doc_type_abbr')
    op.drop_column('Tbl_Document_Metadata', 'law_doc_type')
    op.drop_column('Tbl_Document_Metadata', 'source')
    op.drop_column('Tbl_Document_Metadata', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tbl_Document_Metadata', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('law_doc_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('law_doc_type_abbr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('url_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('teu', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('document_url_source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('valid_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Tbl_Document_Metadata', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('Tbl_Document_Metadata', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Tbl_Document_Metadata', 'removing_other_law')
    op.drop_column('Tbl_Document_Metadata', 'changed_by_other_law')
    op.drop_column('Tbl_Document_Metadata', 'about')
    # ### end Alembic commands ###
