"""User Role Permission tables

Revision ID: 817275a8b522
Revises: 
Create Date: 2025-01-19 09:41:51.249881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817275a8b522'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tbl_Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_name', sa.String(), nullable=False),
    sa.Column('permission_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Permissions_id'), 'Tbl_Permissions', ['id'], unique=False)
    op.create_index(op.f('ix_Tbl_Permissions_permission_name'), 'Tbl_Permissions', ['permission_name'], unique=False)
    op.create_table('Tbl_Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Roles_id'), 'Tbl_Roles', ['id'], unique=False)
    op.create_index(op.f('ix_Tbl_Roles_role_name'), 'Tbl_Roles', ['role_name'], unique=False)
    op.create_table('Tbl_Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Users_email'), 'Tbl_Users', ['email'], unique=True)
    op.create_index(op.f('ix_Tbl_Users_full_name'), 'Tbl_Users', ['full_name'], unique=False)
    op.create_index(op.f('ix_Tbl_Users_id'), 'Tbl_Users', ['id'], unique=False)
    op.create_table('Tbl_Role_Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['Tbl_Permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Tbl_Roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_Role_Permissions_id'), 'Tbl_Role_Permissions', ['id'], unique=False)
    op.create_table('Tbl_User_Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['Tbl_Roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Tbl_Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_User_Role_id'), 'Tbl_User_Role', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tbl_User_Role_id'), table_name='Tbl_User_Role')
    op.drop_table('Tbl_User_Role')
    op.drop_index(op.f('ix_Tbl_Role_Permissions_id'), table_name='Tbl_Role_Permissions')
    op.drop_table('Tbl_Role_Permissions')
    op.drop_index(op.f('ix_Tbl_Users_id'), table_name='Tbl_Users')
    op.drop_index(op.f('ix_Tbl_Users_full_name'), table_name='Tbl_Users')
    op.drop_index(op.f('ix_Tbl_Users_email'), table_name='Tbl_Users')
    op.drop_table('Tbl_Users')
    op.drop_index(op.f('ix_Tbl_Roles_role_name'), table_name='Tbl_Roles')
    op.drop_index(op.f('ix_Tbl_Roles_id'), table_name='Tbl_Roles')
    op.drop_table('Tbl_Roles')
    op.drop_index(op.f('ix_Tbl_Permissions_permission_name'), table_name='Tbl_Permissions')
    op.drop_index(op.f('ix_Tbl_Permissions_id'), table_name='Tbl_Permissions')
    op.drop_table('Tbl_Permissions')
    # ### end Alembic commands ###
