"""File Storage table

Revision ID: a3535421f1ff
Revises: 241a9ac2b867
Create Date: 2025-01-19 10:17:06.526623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3535421f1ff'
down_revision: Union[str, None] = '241a9ac2b867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tbl_File_Storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_file', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['Tbl_Documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Tbl_File_Storage_document_id'), 'Tbl_File_Storage', ['document_id'], unique=False)
    op.create_index(op.f('ix_Tbl_File_Storage_id'), 'Tbl_File_Storage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tbl_File_Storage_id'), table_name='Tbl_File_Storage')
    op.drop_index(op.f('ix_Tbl_File_Storage_document_id'), table_name='Tbl_File_Storage')
    op.drop_table('Tbl_File_Storage')
    # ### end Alembic commands ###
