"""Documents Hash

Revision ID: d8be2130d1e4
Revises: 20c2fabf37d9
Create Date: 2025-03-22 20:21:48.598144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8be2130d1e4'
down_revision: Union[str, None] = '20c2fabf37d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tbl_Documents', sa.Column('document_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tbl_Documents', 'document_hash')
    # ### end Alembic commands ###
