ASSERTED_SNAKE_CASE_1 = "Tbl_Anaconda"
ASSERTED_SNAKE_CASE_2 = "Tbl_Anaconda_2"
ASSERTED_SNAKE_CASE_3 = "Tbl_Anaconda_Prompt_123"
ASSERTED_SNAKE_CASE_4 = "Tbl_Intelligent_Agent"
ASSERTED_SNAKE_CASE_5 = "Tbl_Scraped_PDF"

SNAKE_CASE_1 = "TblAnaconda"
SNAKE_CASE_2 = "TblAnaconda2"
SNAKE_CASE_3 = "TblAnacondaPrompt123"
SNAKE_CASE_4 = "TblIntelligentAgent"
SNAKE_CASE_5 = "TblScrapedPDF"
