KEYWORD_ARGS_HOST = "host"
KEYWORD_ARGS_IP_ADDR = "ip_address"
KEYWORD_ARGS_MODEL_TAG = "model_tag"
KEYWORD_ARGS_PORT = "port"
KEYWORD_ARGS_TAG = "tag"

LLM_SERVICE_GROQ = "groq"
LLM_SERVICE_HUGGINGFACE = "huggingface"
LLM_SERVICE_OLLAMA = "ollama"
LLM_SERVICE_OPENAI = "openai"

OLLAMA_DEFAULT_PORT = 11434
