# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint & Testing

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Lint with Pylint
      run: |
        # Check Pylintrc file
        if [ ! -f ".pylintrc" ]; then
            echo "Pylintrc file not found. Creating one..."
            pylint --generate-rcfile > .pylintrc
        fi

        # Run Pylint with Minimum Score 7.0
        pip install --force-reinstall --no-deps -r requirements.txt --quiet
        score=$(pylint AskEmploymentLaw --exit-zero | grep "Your code has been rated at" | awk '{print $7}' | cut -d/ -f1)
        echo "Pylint Score: $score"
        if (( $(echo "$score < 7.0" | bc -l) )); then
          echo "Lint score too low! Failing."
          echo "Below is the output of pylint:"
          pylint AskEmploymentLaw
          exit 1
        fi
    - name: Run tests
      run: |
        pip install --upgrade pytest-cov pytest-metadata
        pytest --maxfail=1 --disable-pytest-warnings --ignore=tests/core/test_llm_adapters.py
